CREATE TABLE IF NOT EXISTS REQ_WIRELESS_CONTRACT (
    CONTRACT_NO BIGINT PRIMARY KEY,
    CUSTOMER_NO BIGINT NOT NULL,
    PLAN_CODE VARCHAR(20) NOT NULL,
    ACTIVATION_DATE DATE,
    STATUS VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS BAT_PREPARATION_TARGET (
    REP_CONTRACT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    DOMAIN_TYPE VARCHAR(20) NOT NULL,
    EXTRA_INFO VARCHAR(4000),
    PRIMARY KEY (REP_CONTRACT_ID, DOMAIN_TYPE)
);