CREATE TABLE IF NOT EXISTS REQ_WIRELESS_CONTRACT (
    CONTRACT_NO BIGINT PRIMARY KEY,
    CUSTOMER_NO BIGINT NOT NULL,
    PLAN_CODE VARCHAR(20) NOT NULL,
    ACTIVATION_DATE DATE,
    STATUS VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS BAT_PREPARATION_TARGET (
    REP_CONTRACT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    DOMAIN_TYPE VARCHAR(20) NOT NULL,
    EXTRA_INFO VARCHAR(4000),
    PRIMARY KEY (REP_CONTRACT_ID, DOMAIN_TYPE)
);

/* --- [v0.03] 신규 추가 테이블 --- */

/* Step 1의 결과물 (임시 테이블 1) */
CREATE TABLE IF NOT EXISTS STAGING_CONTRACTS (
    CONTRACT_NO BIGINT PRIMARY KEY,
    CUSTOMER_NO BIGINT NOT NULL,
    GRADE VARCHAR(10),
    ACTIVATION_DATE DATE
);

/* Step 2의 결과물 (임시 테이블 2) */
CREATE TABLE IF NOT EXISTS STAGING_USAGE (
    CONTRACT_NO BIGINT PRIMARY KEY,
    TOTAL_USAGE_AMOUNT DECIMAL(15, 2)
);

/* Step 3 Enricher가 사용할 원천 테이블 (고객 정보) */
CREATE TABLE IF NOT EXISTS CUSTOMER_INFO (
    CUSTOMER_NO BIGINT PRIMARY KEY,
    GRADE VARCHAR(10) NOT NULL,
    NAME VARCHAR(50)
);

/* Step 2가 사용할 원천 테이블 (사용량 원천) */
CREATE TABLE IF NOT EXISTS USAGE_RAW_DATA (
    USAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTRACT_NO BIGINT NOT NULL,
    USAGE_AMOUNT DECIMAL(10, 2)
);